public class AccountTriggerHandler implements TriggerInterface{
    public static void beforeInsert(List<sObject> newRecordList){
        
    }
    public static void afterInsert(List<sObject> newRecordList, map<Id, sObject> newRecordMap){
        
    }
    public static void beforeUpdate(map<Id, sObject> newRecordMap, map<Id, sObject> oldRecordMap){
        
    }
    public static void afterUpdate(map<Id, sObject> newRecordMap, map<Id, sObject> oldRecordMap){
        
    }
    public static void beforeDelete(List<sObject> oldRecordList, map<Id, sObject> oldRecordMap){
        
    }
    public static void afterDelete(map<Id, sObject> oldRecordMap){
        
    }
}