@istest

public class QQ9_Test {
   @isTest
    static void test()
    {
        list<account> accList= new list<account>();
        for(integer i=0;i<50;i++)
        {
            account acc = new account();
            acc.name= 'Nmae';
           
            acclist.add(acc);
        }
        insert acclist;
        
        test.startTest();
        QQ9 qtest = new QQ9();
        Qtest.search();
        
        test.stopTest();
    }
    
}